In [1]:
!pip install -q langchain-text-splitters

In [20]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [26]:
from langchain_text_splitters import (
    CharacterTextSplitter,
    RecursiveCharacterTextSplitter,
    MarkdownHeaderTextSplitter,
    NLTKTextSplitter
)
from pathlib import Path
import re
import nltk

import pandas as pd

In [8]:

PASTA = Path("/content/sample_data/mds")

arquivos = list(PASTA.glob("**/*.md"))

#print(f"Arquivos encontrados: {len(arquivos)}")

documentos = []

for arquivo in arquivos:
    texto = arquivo.read_text(encoding="utf-8")

    documentos.append({
        "arquivo": arquivo.name,
        "caminho": str(arquivo),
        #"texto": texto
    })

print(documentos)

# passa pelos arquivos
for item in documentos:
    print("Arquivo:", item['arquivo'])
    print("Caminho:", item['caminho'])

[{'arquivo': 'bert_pretraining.md', 'caminho': '/content/sample_data/mds/bert_pretraining.md'}, {'arquivo': 'attention_is_all_you_need.md', 'caminho': '/content/sample_data/mds/attention_is_all_you_need.md'}]
Arquivo: bert_pretraining.md
Caminho: /content/sample_data/mds/bert_pretraining.md
Arquivo: attention_is_all_you_need.md
Caminho: /content/sample_data/mds/attention_is_all_you_need.md

In [44]:
def chunk_calc(text, tamanho, overlap=0):
    splitter = CharacterTextSplitter(
        separator="",
        chunk_size=tamanho,
        chunk_overlap=overlap
    )

    chunks = splitter.split_text(text)
    return chunks

# Teste 7 - Por parágrafo

In [72]:
# ! Porém, há uma pegadinha: RecursiveCharacterTextSplitter ainda respeita chunk_size. Então isso não é exatamente um "splitter de parágrafos puro" se um parágrafo for muito grande.
# Teste 7
def analise_paragrafos(text, arquivo):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=999999,
        chunk_overlap=0,
        separators=["\n\n"]
    )


    chunks = splitter.create_documents([text])

    tamanhos = [
        len(chunk.page_content)
        for chunk in chunks
    ]

    metadados = {
        "arquivo": arquivo.name,
        "caminho": str(arquivo),
        "teste": 7,
        "estrategia": "Por parágrafo"
    }

    chunks = splitter.create_documents(
        [texto],
        metadatas=[metadados]
    )

    return {
        "Qtd. chunks": len(chunks),
        "Tamanho médio": round(sum(tamanhos) / len(tamanhos), 2),
        "Tamanho mínimo": min(tamanhos),
        "Tamanho máximo": max(tamanhos)
    }

analise = analise_paragrafos(texto, arquivo)

print(analise)

{'Qtd. chunks': 1, 'Tamanho médio': 70235.0, 'Tamanho mínimo': 70235, 'Tamanho máximo': 70235}

In [77]:
resultados_teste7 = []

for arquivo in arquivos:

    texto = arquivo.read_text(encoding="utf-8")

    analise = analise_paragrafos(
        texto,
        arquivo
    )

    resultados_teste7.append({
        "Arquivo": arquivo.name,
        **analise
    })

In [78]:
df_teste7 = pd.DataFrame(resultados_teste7)

display(df_teste7)

,Arquivo,Qtd. chunks,Tamanho médio,Tamanho mínimo,Tamanho máximo
0,bert_pretraining.md,1,70235.0,70235,70235
1,attention_is_all_you_need.md,1,48957.0,48957,48957

# Teste 8 - Sentenças agrupadas

In [95]:
# Teste 8

def analise_sentencas(texto, arquivo):

    splitter = NLTKTextSplitter()

    sentencas = splitter.split_text(texto)

    chunks = []

    for i in range(0, len(sentencas), 3):

        grupo = sentencas[i:i + 3]

        texto_chunk = " ".join(grupo)

        chunks.append({
            "texto": texto_chunk,
            "quantidade_sentencas": len(grupo),
            "metadados": {
                "arquivo": arquivo.name,
                "caminho": str(arquivo),
                "teste": 8,
                "estrategia": "Sentenças agrupadas",
                "sentencas": len(grupo)
            }
        })

    return chunks

In [82]:
def analisar_teste_8(chunks):

    tamanhos = [
        len(chunk["texto"])
        for chunk in chunks
    ]

    return {
        "Qtd. chunks": len(chunks),
        "Tamanho médio": round(sum(tamanhos) / len(tamanhos), 2),
        "Tamanho mínimo": min(tamanhos),
        "Tamanho máximo": max(tamanhos)
    }

In [96]:
resultados_teste8 = []

for arquivo in arquivos:

    texto = arquivo.read_text(encoding="utf-8")

    chunks = analise_sentencas(
        texto,
        arquivo
    )

    analise = analisar_teste_8(chunks)

    resultados_teste8.append({
        "Arquivo": arquivo.name,
        "Teste": 8,
        "Estratégia": "Sentenças agrupadas",
        "Configuração": "3 sentenças por chunk",
        **analise
    })

WARNING:langchain_text_splitters.base:Created a chunk of size 9506, which is longer than the specified 4000

In [97]:
import pandas as pd

df_teste8 = pd.DataFrame(resultados_teste8)

display(df_teste8)

,Arquivo,Teste,Estratégia,Configuração,Qtd. chunks,Tamanho médio,Tamanho mínimo,Tamanho máximo
0,bert_pretraining.md,8,Sentenças agrupadas,3 sentenças por chunk,7,10490.71,4432,11868
1,attention_is_all_you_need.md,8,Sentenças agrupadas,3 sentenças por chunk,5,10086.60,1620,14045

In [98]:
for arquivo in arquivos:

    texto = arquivo.read_text(encoding="utf-8")

    chunks = analise_sentencas(
        texto,
        arquivo
    )

    print(f"\n\n{'=' * 60}")
    print(f"ARQUIVO: {arquivo.name}")
    print(f"{'=' * 60}")

    for i, chunk in enumerate(chunks[:3], start=1):

        print(f"\n--- Chunk {i} ---")
        print(chunk["texto"])

WARNING:langchain_text_splitters.base:Created a chunk of size 9506, which is longer than the specified 4000

============================================================
ARQUIVO: bert_pretraining.md
============================================================

--- Chunk 1 ---
## BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding

Jacob Devlin Ming-Wei Chang Kenton Lee Kristina Toutanova

Google AI Language

{ jacobdevlin,mingweichang,kentonl,kristout } @google.com

## Abstract

We introduce a new language representation model called BERT , which stands for B idirectional E ncoder R epresentations from T ransformers.

Unlike recent language representation models (Peters et al., 2018a; Radford et al., 2018), BERT is designed to pretrain deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers.

As a result, the pre-trained BERT model can be finetuned with just one additional output layer to create state-of-the-art models for a wide range of tasks, such as question answering and language inference, without substantial taskspecific architecture modifications.

BERT is conceptually simple and empirically powerful.

It obtains new state-of-the-art results on eleven natural language processing tasks, including pushing the GLUE score to 80.5% (7.7% point absolute improvement), MultiNLI accuracy to 86.7% (4.6% absolute improvement), SQuAD v1.1 question answering Test F1 to 93.2 (1.5 point absolute improvement) and SQuAD v2.0 Test F1 to 83.1 (5.1 point absolute improvement).

## 1 Introduction

Language model pre-training has been shown to be effective for improving many natural language processing tasks (Dai and Le, 2015; Peters et al., 2018a; Radford et al., 2018; Howard and Ruder, 2018).

These include sentence-level tasks such as natural language inference (Bowman et al., 2015; Williams et al., 2018) and paraphrasing (Dolan and Brockett, 2005), which aim to predict the relationships between sentences by analyzing them holistically, as well as token-level tasks such as named entity recognition and question answering, where models are required to produce fine-grained output at the token level (Tjong Kim Sang and De Meulder, 2003; Rajpurkar et al., 2016).

There are two existing strategies for applying pre-trained language representations to downstream tasks: feature-based and fi ne-tuning .

The feature-based approach, such as ELMo (Peters et al., 2018a), uses task-specific architectures that include the pre-trained representations as additional features.

The fine-tuning approach, such as the Generative Pre-trained Transformer (OpenAI GPT) (Radford et al., 2018), introduces minimal task-specific parameters, and is trained on the downstream tasks by simply fine-tuning all pretrained parameters.

The two approaches share the same objective function during pre-training, where they use unidirectional language models to learn general language representations.

We argue that current techniques restrict the power of the pre-trained representations, especially for the fine-tuning approaches.

The major limitation is that standard language models are unidirectional, and this limits the choice of architectures that can be used during pre-training.

For example, in OpenAI GPT, the authors use a left-toright architecture, where every token can only attend to previous tokens in the self-attention layers of the Transformer (Vaswani et al., 2017).

Such restrictions are sub-optimal for sentence-level tasks, and could be very harmful when applying finetuning based approaches to token-level tasks such as question answering, where it is crucial to incorporate context from both directions.

In this paper, we improve the fine-tuning based approaches by proposing BERT: B idirectional E ncoder R epresentations from T ransformers.

BERT alleviates the previously mentioned unidirectionality constraint by using a 'masked language model' (MLM) pre-training objective, inspired by the Cloze task (Taylor, 1953).

The masked language model randomly masks some of the tokens from the input, and the objective is to predict the original vocabulary id of the masked word based only on its context. The masked language model randomly masks some of the tokens from the input, and the objective is to predict the original vocabulary id of the masked word based only on its context.

Unlike left-toright language model pre-training, the MLM objective enables the representation to fuse the left and the right context, which allows us to pretrain a deep bidirectional Transformer.

In addition to the masked language model, we also use a 'next sentence prediction' task that jointly pretrains text-pair representations.

The contributions of our paper are as follows:

- We demonstrate the importance of bidirectional pre-training for language representations.

Unlike Radford et al.

(2018), which uses unidirectional language models for pre-training, BERT uses masked language models to enable pretrained deep bidirectional representations.

This is also in contrast to Peters et al.

(2018a), which uses a shallow concatenation of independently trained left-to-right and right-to-left LMs.

- Weshow that pre-trained representations reduce the need for many heavily-engineered taskspecific architectures.

BERT is the first finetuning based representation model that achieves state-of-the-art performance on a large suite of sentence-level and token-level tasks, outperforming many task-specific architectures.

- BERT advances the state of the art for eleven NLP tasks.

The code and pre-trained models are available at https://github.com/ google-research/bert .

## 2 Related Work

There is a long history of pre-training general language representations, and we briefly review the most widely-used approaches in this section.

## 2.1 Unsupervised Feature-based Approaches

Learning widely applicable representations of words has been an active area of research for decades, including non-neural (Brown et al., 1992; Ando and Zhang, 2005; Blitzer et al., 2006) and neural (Mikolov et al., 2013; Pennington et al., 2014) methods.

Pre-trained word embeddings are an integral part of modern NLP systems, offering significant improvements over embeddings learned from scratch (Turian et al., 2010).

To pretrain word embedding vectors, left-to-right language modeling objectives have been used (Mnih and Hinton, 2009), as well as objectives to discriminate correct from incorrect words in left and right context (Mikolov et al., 2013).

These approaches have been generalized to coarser granularities, such as sentence embeddings (Kiros et al., 2015; Logeswaran and Lee, 2018) or paragraph embeddings (Le and Mikolov, 2014).

To train sentence representations, prior work has used objectives to rank candidate next sentences (Jernite et al., 2017; Logeswaran and Lee, 2018), left-to-right generation of next sentence words given a representation of the previous sentence (Kiros et al., 2015), or denoising autoencoder derived objectives (Hill et al., 2016).

ELMo and its predecessor (Peters et al., 2017, 2018a) generalize traditional word embedding research along a different dimension.

They extract context-sensitive features from a left-to-right and a right-to-left language model.

The contextual representation of each token is the concatenation of the left-to-right and right-to-left representations.

When integrating contextual word embeddings with existing task-specific architectures, ELMo advances the state of the art for several major NLP benchmarks (Peters et al., 2018a) including question answering (Rajpurkar et al., 2016), sentiment analysis (Socher et al., 2013), and named entity recognition (Tjong Kim Sang and De Meulder, 2003).

Melamud et al.

(2016) proposed learning contextual representations through a task to predict a single word from both left and right context using LSTMs.

Similar to ELMo, their model is feature-based and not deeply bidirectional.

Fedus et al.

(2018) shows that the cloze task can be used to improve the robustness of text generation models. Similar to ELMo, their model is feature-based and not deeply bidirectional.

Fedus et al.

(2018) shows that the cloze task can be used to improve the robustness of text generation models.

## 2.2 Unsupervised Fine-tuning Approaches

As with the feature-based approaches, the first works in this direction only pre-trained word embedding parameters from unlabeled text (Collobert and Weston, 2008).

More recently, sentence or document encoders which produce contextual token representations have been pre-trained from unlabeled text and fine-tuned for a supervised downstream task (Dai and Le, 2015; Howard and Ruder, 2018; Radford et al., 2018).

The advantage of these approaches is that few parameters need to be learned from scratch.

At least partly due to this advantage, OpenAI GPT (Radford et al., 2018) achieved previously state-of-the-art results on many sentencelevel tasks from the GLUE benchmark (Wang et al., 2018a).

Left-to-right language modeling and auto-encoder objectives have been used for pre-training such models (Howard and Ruder, 2018; Radford et al., 2018; Dai and Le, 2015).

Figure 1: Overall pre-training and fine-tuning procedures for BERT.

Apart from output layers, the same architectures are used in both pre-training and fine-tuning.

The same pre-trained model parameters are used to initialize models for different down-stream tasks.

During fine-tuning, all parameters are fine-tuned.

[CLS] is a special symbol added in front of every input example, and [SEP] is a special separator token (e.g.

separating questions/answers).

<!-- image -->

## 2.3 Transfer Learning from Supervised Data

There has also been work showing effective transfer from supervised tasks with large datasets, such as natural language inference (Conneau et al., 2017) and machine translation (McCann et al., 2017).

Computer vision research has also demonstrated the importance of transfer learning from large pre-trained models, where an effective recipe is to fine-tune models pre-trained with ImageNet (Deng et al., 2009; Yosinski et al., 2014).

## 3 BERT

We introduce BERT and its detailed implementation in this section.

There are two steps in our framework: pre-training and fi ne-tuning .

During pre-training, the model is trained on unlabeled data over different pre-training tasks.

For finetuning, the BERT model is first initialized with the pre-trained parameters, and all of the parameters are fine-tuned using labeled data from the downstream tasks.

Each downstream task has separate fine-tuned models, even though they are initialized with the same pre-trained parameters.

The question-answering example in Figure 1 will serve as a running example for this section.

A distinctive feature of BERT is its unified architecture across different tasks.

There is minimal difference between the pre-trained architecture and the final downstream architecture.

Model Architecture BERT's model architecture is a multi-layer bidirectional Transformer encoder based on the original implementation described in Vaswani et al.

(2017) and released in the tensor2tensor library.

1 Because the use of Transformers has become common and our implementation is almost identical to the original, we will omit an exhaustive background description of the model architecture and refer readers to Vaswani et al.

(2017) as well as excellent guides such as 'The Annotated Transformer.'

2

In this work, we denote the number of layers (i.e., Transformer blocks) as L , the hidden size as H , and the number of self-attention heads as A .

3 We primarily report results on two model sizes: BERTBASE (L=12, H=768, A=12, Total Parameters=110M) and BERTLARGE (L=24, H=1024, A=16, Total Parameters=340M).

BERTBASE was chosen to have the same model size as OpenAI GPT for comparison purposes.

Critically, however, the BERT Transformer uses bidirectional self-attention, while the GPT Transformer uses constrained self-attention where every token can only attend to context to its left.

--- Chunk 2 ---
Critically, however, the BERT Transformer uses bidirectional self-attention, while the GPT Transformer uses constrained self-attention where every token can only attend to context to its left.

4

1 https://github.com/tensorflow/tensor2tensor

2 http://nlp.seas.harvard.edu/2018/04/03/attention.html

3

In all cases we set the feed-forward/filter size to be 4 H , i.e., 3072 for the H = 768 and 4096 for the H = 1024 .

4 We note that in the literature the bidirectional Trans-

Input/Output Representations To make BERT handle a variety of down-stream tasks, our input representation is able to unambiguously represent both a single sentence and a pair of sentences (e.g., 〈 Question, Answer 〉 ) in one token sequence.

Throughout this work, a 'sentence' can be an arbitrary span of contiguous text, rather than an actual linguistic sentence.

A 'sequence' refers to the input token sequence to BERT, which may be a single sentence or two sentences packed together.

We use WordPiece embeddings (Wu et al., 2016) with a 30,000 token vocabulary.

The first token of every sequence is always a special classification token ( [CLS] ).

The final hidden state corresponding to this token is used as the aggregate sequence representation for classification tasks.

Sentence pairs are packed together into a single sequence.

We differentiate the sentences in two ways.

First, we separate them with a special token ( [SEP] ).

Second, we add a learned embedding to every token indicating whether it belongs to sentence A or sentence B .

As shown in Figure 1, we denote input embedding as E , the final hidden vector of the special [CLS] token as C ∈ R H , and the final hidden vector for the i th input token as T i ∈ R H .

For a given token, its input representation is constructed by summing the corresponding token, segment, and position embeddings.

A visualization of this construction can be seen in Figure 2.

## 3.1 Pre-training BERT

Unlike Peters et al.

(2018a) and Radford et al.

(2018), we do not use traditional left-to-right or right-to-left language models to pre-train BERT.

Instead, we pre-train BERT using two unsupervised tasks, described in this section.

This step is presented in the left part of Figure 1.

Task #1: Masked LM Intuitively, it is reasonable to believe that a deep bidirectional model is strictly more powerful than either a left-to-right model or the shallow concatenation of a left-toright and a right-to-left model.

Unfortunately, standard conditional language models can only be trained left-to-right or right-to-left, since bidirectional conditioning would allow each word to indirectly 'see itself', and the model could trivially predict the target word in a multi-layered context.

former is often referred to as a 'Transformer encoder' while the left-context-only version is referred to as a 'Transformer decoder' since it can be used for text generation.

In order to train a deep bidirectional representation, we simply mask some percentage of the input tokens at random, and then predict those masked tokens.

We refer to this procedure as a 'masked LM' (MLM), although it is often referred to as a Cloze task in the literature (Taylor, 1953).

In this case, the final hidden vectors corresponding to the mask tokens are fed into an output softmax over the vocabulary, as in a standard LM.

In all of our experiments, we mask 15% of all WordPiece tokens in each sequence at random.

In contrast to denoising auto-encoders (Vincent et al., 2008), we only predict the masked words rather than reconstructing the entire input.

Although this allows us to obtain a bidirectional pre-trained model, a downside is that we are creating a mismatch between pre-training and fine-tuning, since the [MASK] token does not appear during fine-tuning.

To mitigate this, we do not always replace 'masked' words with the actual [MASK] token.

The training data generator chooses 15% of the token positions at random for prediction. To mitigate this, we do not always replace 'masked' words with the actual [MASK] token.

The training data generator chooses 15% of the token positions at random for prediction.

If the i -th token is chosen, we replace the i -th token with (1) the [MASK] token 80% of the time (2) a random token 10% of the time (3) the unchanged i -th token 10% of the time.

Then, T i will be used to predict the original token with cross entropy loss.

We compare variations of this procedure in Appendix C.2.

Task #2: Next Sentence Prediction (NSP) Many important downstream tasks such as Question Answering (QA) and Natural Language Inference (NLI) are based on understanding the relationship between two sentences, which is not directly captured by language modeling.

In order to train a model that understands sentence relationships, we pre-train for a binarized next sentence prediction task that can be trivially generated from any monolingual corpus.

Specifically, when choosing the sentences A and B for each pretraining example, 50% of the time B is the actual next sentence that follows A (labeled as IsNext ), and 50% of the time it is a random sentence from the corpus (labeled as NotNext ).

As we show in Figure 1, C is used for next sentence prediction (NSP).

5 Despite its simplicity, we demonstrate in Section 5.1 that pre-training towards this task is very beneficial to both QA and NLI.

6

5 The final model achieves 97%-98% accuracy on NSP.

6 The vector C is not a meaningful sentence representation without fine-tuning, since it was trained with NSP.

Figure 2: BERT input representation.

The input embeddings are the sum of the token embeddings, the segmentation embeddings and the position embeddings.

<!-- image -->

The NSP task is closely related to representationlearning objectives used in Jernite et al.

(2017) and Logeswaran and Lee (2018).

However, in prior work, only sentence embeddings are transferred to down-stream tasks, where BERT transfers all parameters to initialize end-task model parameters.

Pre-training data The pre-training procedure largely follows the existing literature on language model pre-training.

For the pre-training corpus we use the BooksCorpus (800M words) (Zhu et al., 2015) and English Wikipedia (2,500M words).

For Wikipedia we extract only the text passages and ignore lists, tables, and headers.

It is critical to use a document-level corpus rather than a shuffled sentence-level corpus such as the Billion Word Benchmark (Chelba et al., 2013) in order to extract long contiguous sequences.

## 3.2 Fine-tuning BERT

Fine-tuning is straightforward since the selfattention mechanism in the Transformer allows BERT to model many downstream taskswhether they involve single text or text pairs-by swapping out the appropriate inputs and outputs.

For applications involving text pairs, a common pattern is to independently encode text pairs before applying bidirectional cross attention, such as Parikh et al.

(2016); Seo et al.

(2017).

BERT instead uses the self-attention mechanism to unify these two stages, as encoding a concatenated text pair with self-attention effectively includes bidirectional cross attention between two sentences.

For each task, we simply plug in the taskspecific inputs and outputs into BERT and finetune all the parameters end-to-end.

At the input, sentence A and sentence B from pre-training are analogous to (1) sentence pairs in paraphrasing, (2) hypothesis-premise pairs in entailment, (3) question-passage pairs in question answering, and

(4) a degenerate text-∅ pair in text classification or sequence tagging.

At the output, the token representations are fed into an output layer for tokenlevel tasks, such as sequence tagging or question answering, and the [CLS] representation is fed into an output layer for classification, such as entailment or sentiment analysis.



# Teste 9: Recursivo (separadores hierárquicos)

In [99]:
# # Teste 9: Recursivo (separadores hierárquicos)
# def analisar_recursivo(text):
#   sp9 = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50, separators=["\n\n", "\n", " ", ""])
#   #print("Quantidade de chunks recursivos:", len(sp9.split_text(text)))

#   return sp9

#   from langchain_text_splitters import RecursiveCharacterTextSplitter


def analise_recursivo(texto, arquivo):

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=50,
        separators=[
            "\n\n",
            "\n",
            " ",
            ""
        ]
    )

    documentos = splitter.create_documents(
        [texto],
        metadatas=[{
            "arquivo": arquivo.name,
            "caminho": str(arquivo),
            "teste": 9,
            "estrategia": "Recursive Character",
            "chunk_size": 500,
            "chunk_overlap": 50
        }]
    )

    return documentos

In [90]:
def analisar_chunks_documentos(chunks):

    tamanhos = [
        len(chunk.page_content)
        for chunk in chunks
    ]

    return {
        "Qtd. chunks": len(chunks),
        "Tamanho médio": round(sum(tamanhos) / len(tamanhos), 2),
        "Tamanho mínimo": min(tamanhos),
        "Tamanho máximo": max(tamanhos)
    }

In [100]:
chunks_teste9 = analise_recursivo(
    texto,
    arquivo
)

print("Quantidade de chunks:", len(chunks_teste9))

for i, chunk in enumerate(chunks_teste9[:3], start=1):

    print(f"\n===== CHUNK {i} =====")
    print(chunk.page_content)

    print("\nMetadados:")
    print(chunk.metadata)

    analise = analisar_chunks_documentos(chunks_teste9)

    print(analise)

Quantidade de chunks: 137

===== CHUNK 1 =====
Provided proper attribution is provided, Google hereby grants permission to reproduce the tables and figures in this paper solely for use in journalistic or scholarly works.

## Attention Is All You Need

Ashish Vaswani ∗ Google Brain avaswani@google.com Noam Shazeer ∗ Google Brain noam@google.com

Metadados:
{'arquivo': 'attention_is_all_you_need.md', 'caminho': '/content/sample_data/mds/attention_is_all_you_need.md', 'teste': 9, 'estrategia': 'Recursive Character', 'chunk_size': 500, 'chunk_overlap': 50}
{'Qtd. chunks': 137, 'Tamanho médio': 364.13, 'Tamanho mínimo': 26, 'Tamanho máximo': 499}

===== CHUNK 2 =====
Llion Jones ∗ Google Research llion@google.com Niki Parmar ∗ Google Research nikip@google.com Aidan N. Gomez ∗ † University of Toronto aidan@cs.toronto.edu Jakob Uszkoreit ∗ Google Research usz@google.com Łukasz Kaiser ∗ Google Brain lukaszkaiser@google.com Illia Polosukhin ∗ ‡

illia.polosukhin@gmail.com

## Abstract

Metadados:
{'arquivo': 'attention_is_all_you_need.md', 'caminho': '/content/sample_data/mds/attention_is_all_you_need.md', 'teste': 9, 'estrategia': 'Recursive Character', 'chunk_size': 500, 'chunk_overlap': 50}
{'Qtd. chunks': 137, 'Tamanho médio': 364.13, 'Tamanho mínimo': 26, 'Tamanho máximo': 499}

===== CHUNK 3 =====
The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being

Metadados:
{'arquivo': 'attention_is_all_you_need.md', 'caminho': '/content/sample_data/mds/attention_is_all_you_need.md', 'teste': 9, 'estrategia': 'Recursive Character', 'chunk_size': 500, 'chunk_overlap': 50}
{'Qtd. chunks': 137, 'Tamanho médio': 364.13, 'Tamanho mínimo': 26, 'Tamanho máximo': 499}

In [101]:
resultados_teste9 = []

for arquivo in arquivos:

    texto = arquivo.read_text(encoding="utf-8")

    chunks = analise_recursivo(
        texto,
        arquivo
    )

    analise = analisar_chunks_documentos(chunks)

    resultados_teste9.append({
        "Arquivo": arquivo.name,
        "Teste": 9,
        "Estratégia": "Recursive Character",
        "Configuração": "500 caracteres, overlap 50",
        **analise
    })

df_teste9 = pd.DataFrame(resultados_teste9)

display(df_teste9)

,Arquivo,Teste,Estratégia,Configuração,Qtd. chunks,Tamanho médio,Tamanho mínimo,Tamanho máximo
0,bert_pretraining.md,9,Recursive Character,"500 caracteres, overlap 50",201,356.39,9,499
1,attention_is_all_you_need.md,9,Recursive Character,"500 caracteres, overlap 50",137,364.13,26,499

# Teste 10: Por seção / heading do Markdown

In [103]:
# # Teste 10: Por seção / heading do Markdown
# def analisar_markdown(text):
#     headers = [("#", "Header 1"), ("##", "Header 2"), ("###", "Header 3")]
#     sp10 = MarkdownHeaderTextSplitter(headers_to_split_on=headers)
#     docs_md = sp10.split_text(text)
#     chunks_md = [doc.page_content for doc in docs_md]

#     #print("Quantidade de chunks por seção / heading do Markdown:", len(chunks_md))

#     return chunks_md

from langchain_text_splitters import MarkdownHeaderTextSplitter


def teste_10_markdown(texto, arquivo):

    headers = [
        ("#", "Header 1"),
        ("##", "Header 2"),
        ("###", "Header 3")
    ]

    splitter = MarkdownHeaderTextSplitter(
        headers_to_split_on=headers,
        strip_headers=False
    )

    documentos = splitter.split_text(texto)

    # Adicionar informações do arquivo/teste
    for doc in documentos:
        doc.metadata["arquivo"] = arquivo.name
        doc.metadata["caminho"] = str(arquivo)
        doc.metadata["teste"] = 10
        doc.metadata["estrategia"] = "Markdown / estrutura semântica"

    return documentos

In [104]:
def analisar_chunks_documentos(chunks):

    tamanhos = [
        len(chunk.page_content)
        for chunk in chunks
    ]

    return {
        "Qtd. chunks": len(chunks),
        "Tamanho médio": round(sum(tamanhos) / len(tamanhos), 2),
        "Tamanho mínimo": min(tamanhos),
        "Tamanho máximo": max(tamanhos)
    }

In [106]:
resultados_teste10 = []

for arquivo in arquivos:

    texto = arquivo.read_text(encoding="utf-8")

    chunks = teste_10_markdown(
        texto,
        arquivo
    )

    analise = analisar_chunks_documentos(chunks)

    resultados_teste10.append({
        "Arquivo": arquivo.name,
        "Teste": 10,
        "Estratégia": "Markdown / estrutura semântica",
        "Configuração": "#, ##, ###",
        **analise
    })

df_teste10 = pd.DataFrame(resultados_teste10)

display(df_teste10)

,Arquivo,Teste,Estratégia,Configuração,Qtd. chunks,Tamanho médio,Tamanho mínimo,Tamanho máximo
0,bert_pretraining.md,10,Markdown / estrutura semântica,"#, ##, ###",33,2131.33,32,11380
1,attention_is_all_you_need.md,10,Markdown / estrutura semântica,"#, ##, ###",28,1750.11,12,10946

In [51]:
nltk_splitter = NLTKTextSplitter()

def analise_sentencas(text):

    splitter = NLTKTextSplitter()

    sentencas = splitter.split_text(text)

    chunks = [
        " ".join(sentencas[i:i+3])
        for i in range(0, len(sentencas), 3)
    ]

    return chunks

In [102]:
# não sei se precisa, mas apra analisar quantas partes do chunk existem dentro de outros chunks
def contar_chunks_sobrepostos(chunks):

    contador = 0

    for i in range(1, len(chunks)):

        chunk_anterior = chunks[i - 1]
        chunk_atual = chunks[i]

        tamanho_maximo = min(
            len(chunk_anterior),
            len(chunk_atual)
        )

        possui_overlap = False

        for tamanho in range(1, tamanho_maximo + 1):

            if chunk_anterior[-tamanho:] == chunk_atual[:tamanho]:
                possui_overlap = True
                break

        if possui_overlap:
            contador += 1

    return contador

# Analiser os chunks

In [53]:
def analisar_chunks(chunks, chunk_size, chunk_overlap):

    tamanhos = [len(chunk) for chunk in chunks]

    # Quantidade de chunks que possuem overlap
    if chunk_overlap > 0:
        qtd_sobrepostos = contar_chunks_sobrepostos(chunks)
        #qtd_sobrepostos = max(len(chunks) - 1, 0)
    else:
        qtd_sobrepostos = 0

    # Percentual configurado de overlap
    percentual_overlap = (
        chunk_overlap / chunk_size * 100
        if chunk_size > 0
        else 0
    )



    # aqui dá para comparar com oque o embedding vai realmente retornar depois!
    # Estimativa simples:
    # aproximadamente 4 caracteres por token
    total_caracteres = sum(tamanhos)
    tokens_estimados = round(total_caracteres / 4)

    return {
        "Qtd. chunks": len(chunks),
        "Tamanho médio": round(sum(tamanhos) / len(tamanhos), 2),
        "Tamanho mínimo": min(tamanhos),
        "Tamanho máximo": max(tamanhos),
        "Chunks sobrepostos": qtd_sobrepostos,
        "Overlap (%)": round(percentual_overlap, 2),
        "Tokens estimados": tokens_estimados
    }

In [50]:
# Aqui define os testes a serem realizados
testes = [
    {
        "Teste": 1,
        "Estratégia": "Fixo",
        "Configuração": "200 caracteres, overlap 0",
        "chunk_size": 200,
        "chunk_overlap": 0
    },
    {
        "Teste": 2,
        "Estratégia": "Fixo",
        "Configuração": "500 caracteres, overlap 0",
        "chunk_size": 500,
        "chunk_overlap": 0
    },
    {
        "Teste": 3,
        "Estratégia": "Fixo",
        "Configuração": "1000 caracteres, overlap 0",
        "chunk_size": 1000,
        "chunk_overlap": 0
    },
    {
        "Teste": 4,
        "Estratégia": "Fixo",
        "Configuração": "2000 caracteres, overlap 0",
        "chunk_size": 2000,
        "chunk_overlap": 0
    },
    {
        "Teste": 5,
        "Estratégia": "Fixo + overlap",
        "Configuração": "500 caracteres, overlap 50",
        "chunk_size": 500,
        "chunk_overlap": 50
    },
    {
        "Teste": 6,
        "Estratégia": "Fixo + overlap",
        "Configuração": "500 caracteres, overlap 200",
        "chunk_size": 500,
        "chunk_overlap": 200
    }
]

In [54]:
# Aqui é onde as coisas são executadas
# Ele pega os arquivos com o PATH definido lá em cima
# Faz um loop e manda calcular e depois analizar os chunks para retornar oque é pedido
# Ele vai guardando cada resultado dentro de resultados = []

resultados = []

for arquivo in arquivos:

    texto = arquivo.read_text(encoding="utf-8")

    for teste in testes:

        chunks = chunk_calc(
            texto,
            teste["chunk_size"],
            teste["chunk_overlap"]
        )

        analise = analisar_chunks(
            chunks,
            teste["chunk_size"],
            teste["chunk_overlap"]
        )

        resultados.append({
            "Arquivo": arquivo.name,
            "Teste": teste["Teste"],
            "Estratégia": teste["Estratégia"],
            "Configuração": teste["Configuração"],
            **analise
        })

# Cria a tabela
df_resultados = pd.DataFrame(resultados)

display(df_resultados)

,Arquivo,Teste,Estratégia,Configuração,Qtd. chunks,Tamanho médio,Tamanho mínimo,Tamanho máximo,Chunks sobrepostos,Overlap (%),Tokens estimados
0,bert_pretraining.md,1,Fixo,"200 caracteres, overlap 0",352,197.32,35,200,0,0.0,17364
1,bert_pretraining.md,2,Fixo,"500 caracteres, overlap 0",141,496.12,234,500,0,0.0,17488
2,bert_pretraining.md,3,Fixo,"1000 caracteres, overlap 0",71,987.75,234,1000,0,0.0,17532
3,bert_pretraining.md,4,Fixo,"2000 caracteres, overlap 0",36,1950.22,234,2000,0,0.0,17552
4,bert_pretraining.md,5,Fixo + overlap,"500 caracteres, overlap 50",156,497.53,440,500,155,10.0,19404
5,bert_pretraining.md,6,Fixo + overlap,"500 caracteres, overlap 200",234,497.38,335,500,233,40.0,29097
6,attention_is_all_you_need.md,1,Fixo,"200 caracteres, overlap 0",245,192.89,117,200,0,0.0,11814
7,attention_is_all_you_need.md,2,Fixo,"500 caracteres, overlap 0",98,492.66,425,500,0,0.0,12070
8,attention_is_all_you_need.md,3,Fixo,"1000 caracteres, overlap 0",49,993.20,937,1000,0,0.0,12167
9,attention_is_all_you_need.md,4,Fixo,"2000 caracteres, overlap 0",25,1951.04,956,2000,0,0.0,12194
10,attention_is_all_you_need.md,5,Fixo + overlap,"500 caracteres, overlap 50",109,491.54,357,500,108,10.0,13394
11,attention_is_all_you_need.md,6,Fixo + overlap,"500 caracteres, overlap 200",163,492.30,357,500,162,40.0,20061

In [39]:
# TESTE, esta parte é puramente para visualizar e testar como as coisas estavm retornado

for item in documentos:
    item_to_anylise = item['caminho']
    print(item_to_anylise)
    with open(item_to_anylise,"r",encoding="utf-8") as file:
        text = file.read()

    teste1 = chunk_calc(text, 200, 0)
    teste2 = chunk_calc(text, 500, 0)
    teste3 = chunk_calc(text, 1000, 0)
    teste4 = chunk_calc(text, 2000, 0)

    teste5 = chunk_calc(text, 500, 50)
    teste6 = chunk_calc(text, 500, 200)

    test_results_to_analyze = [teste1, teste2, teste3, teste4, teste5, teste6]

    print(f"Tamnho do Chunk teste1: {len(teste1)}")
    print(f"Tamanho do Chunk teste2: {len(teste2)}")
    print(f"Tamanho do Chunk teste3: {len(teste3)}")
    print(f"Tamanho do Chunk teste4: {len(teste4)}")
    print(f"Tamanho do Chunk teste5: {len(teste5)}")
    print(f"Tamanho do Chunk teste6: {len(teste6)}")

    #teste 8
    sentencas = nltk_splitter.split_text(text)
    print(f"Tamanho Sentenças {len(sentencas)}")

    teste9 = analisar_recursivo(text)
    print("Quantidade de chunks recursivos:", len(teste9.split_text(text)))

    teste10 = analisar_markdown(text)
    print("Quantidade de chunks por seção / heading do Markdown:", len(teste10))

/content/sample_data/mds/bert_pretraining.md
Tamnho do Chunk teste1: 352
Tamanho do Chunk teste2: 141
Tamanho do Chunk teste3: 71
Tamanho do Chunk teste4: 36
Tamanho do Chunk teste5: 156
Tamanho do Chunk teste6: 234
Tamanho Sentenças 20
Quantidade de chunks recursivos: 201
Quantidade de chunks por seção / heading do Markdown: 30
/content/sample_data/mds/attention_is_all_you_need.md

WARNING:langchain_text_splitters.base:Created a chunk of size 9506, which is longer than the specified 4000

Tamnho do Chunk teste1: 245
Tamanho do Chunk teste2: 98
Tamanho do Chunk teste3: 49
Tamanho do Chunk teste4: 25
Tamanho do Chunk teste5: 109
Tamanho do Chunk teste6: 163
Tamanho Sentenças 13
Quantidade de chunks recursivos: 137
Quantidade de chunks por seção / heading do Markdown: 27